name: Validacao

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obter codigo
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias
        run: dotnet restore TS-D.sln

      - name: Compilar
        run: dotnet build TS-D.sln --configuration Release --no-restore

      - name: Validar
        run: dotnet test TS-D.sln --configuration Release --no-build
